id: P006767
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ8070
  title: ལམ་རིམ་གྱི་དམིགས་རྣམ་སྐྱོང་ཚུལ།
  author: ''
  volumes:
    89174ffe39a54c8d8cbfdf33e9d67405:
      image_group_id: I1PD96670
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
